title: 'Michael Thramann'
description: "Michael Thramann's personal site"
baseurl: "/"
url: "https://mthramann.github.io"

header_pages:
  - index.md
  - research.md
  - projects.md
  - contact.md

style: dark # dark (default) or light

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console