title: 'Michael Thramann'
description: "Michael Thramann's personal site"
baseurl: "/"
url: "https://mthramann.github.io"

header_pages:
  - index.md
  - projects.md
  - research.md
  - contact.md

footer: 'contact me at <a href="mailto:mthramann@gmail.com">mthramann@gmail.com</a>'

style: dark # dark (default) or light

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
theme: jekyll-theme-minimal